### ISSUE TITLE
NullPointerException error when trying to log into wings-portal

### ISSUE THREAD

**Issue by bmullan** [IKCAP/wings#16]
Installed wings workflow onto tomcat7 running on Ubuntu 14.04 x64bit machine

I can get to the tomcat manager and it shows that the wings-portal war file has been installed ok.
but I cannot reach the wings-portal server?
Pointing my browser to it:
http://10.0.3.224:8080/wings-portal/common/users

I keep getting an error:

HTTP Status 500 - An exception occurred processing JSP page /jsp/login.jsp at line 13

type Exception report message An exception occurred processing JSP page /jsp/login.jsp at line 13

description The server encountered an internal error that prevented it from fulfilling this request.
exception

org.apache.jasper.JasperException: An exception occurred processing JSP page /jsp/login.jsp at line 13

10: <meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
11: <title>Login to Wings</title>
12: <%
13: Config configx = new Config(request);
14: PrintWriter outx = new PrintWriter(out);
15: JSLoader.loadConfigurationJS(outx, configx);
16: JSLoader.loadLoginViewer(outx, configx.getContextRootPath());

Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:568)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:470)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)

root cause

java.lang.NullPointerException
	edu.isi.wings.portal.classes.Config.initializePortalConfig(Config.java:307)
	edu.isi.wings.portal.classes.Config.<init>(Config.java:103)
	org.apache.jsp.jsp.login_jsp._jspService(login_jsp.java:72)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

**Comment by olyerickson** [comment]
Thanks for this thread...

I had the exact error reported by bmullen and followed the Dec 12, 2014 suggestion, which solved the initial error (the portal welcome came up) but I saw the following error when attempting authentication:

HTTP Status 500 - type Exception report

message
description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.NullPointerException
	edu.isi.wings.portal.controllers.DomainController.initializeDomainList(DomainController.java:373)
	edu.isi.wings.portal.controllers.DomainController.<init>(DomainController.java:75)
	edu.isi.wings.portal.classes.Config.initializeUserConfig(Config.java:263)
	edu.isi.wings.portal.classes.Config.<init>(Config.java:122)
	edu.isi.wings.portal.servlets.ManageTemplates.doGet(ManageTemplates.java:52)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.

**Comment by IKCAP** [comment]
Hi John,

Thanks for the stacktrace there. It points to the system not being able to create files in the storage directory. Could it be a permissions issue where the user running tomcat isn't able to write to the storage directory as defined in portal.properties ?

Regards,
Varun

**Comment by olyerickson** [comment]
Thanks Varun, that was a helpful clue! This is what I did:

1. Created /usr/share/tomcat7/storage
2. Created /usr/share/tomcat7/storage/TDB
3. chmod to 777 for both (not sure if this was necessary, or even safe...)
4. Restarted tomcat

I am now able to log in!
