### ISSUE TITLE
"Manage Data" interface is empty

### ISSUE THREAD

**Issue by olyerickson** [IKCAP/wings#19]
As per the Manage Data tutorial http://www.wings-workflows.org/tutorial/manage_data I'm expecting to see a tree under "DataObject"; mine is empty: 
![selection_472](https://cloud.githubusercontent.com/assets/358649/10394724/f7f3443c-6e66-11e5-8550-2b4981126c98.png)

**Comment by IKCAP** [comment]
Could you check that the selected domain is not the "blank" domain ? 

<img width="866" alt="screen shot 2015-10-09 at 14 43 14" src="https://cloud.githubusercontent.com/assets/643851/10395329/3f388082-6e94-11e5-9e1e-39fcf5746a3c.png">

**Comment by olyerickson** [comment]
Yes, that was the problem! I set the default to "TextClassification" and now see:
![selection_473](https://cloud.githubusercontent.com/assets/358649/10395500/5641c028-6e6b-11e5-9078-f6fd3dd6921a.png)

**Comment by IKCAP** [comment]
Yup, that looks good.
