### ISSUE TITLE
"File not on server" for component executable

### ISSUE THREAD

**Issue by olyerickson** [IKCAP/wings#20]
I'm attempted to examine the executable code for a component, using the "HTMLTagCount" component in "CompareFiles" as an example. 

I go into "Manage Components," select HTMLTagCount and click on "Download," then I see...

File not on server
Location: /usr/share/tomcat7/storage/users/olyerickson/CompareFiles/code/library/HTMLTagCount

Where are the executables actually stored?

**Comment by olyerickson** [comment]
More details: contents of directory /usr/share/tomcat7/storage/users/olyerickson/CompareFiles/code/library/

compare  countDuplicates  getSortedWords  html2text  lib  MakeDatasetFromPDFsZip  merge  pdf2text  removePattern  skeleton

So there are some components in there...

**Comment by olyerickson** [comment]
Works for other components in other domains; for example, "Annotate_Best_TemplateMatch" from OpenCV can be downloaded...

**Comment by IKCAP** [comment]
I'm afraid that component is missing in the domain and should be deleted. You could either delete it yourself, or you could install the new domain file here (it is bigger as it has some extra data files):
http://www.wings-workflows.org/domains/CompareFiles.zip

**Comment by olyerickson** [comment]
That was successful; see attached. Also, I seemed to have solved the problem I was experiencing earlier "uploading" domain files from my local drive. 
![selection_475](https://cloud.githubusercontent.com/assets/358649/10398982/09bb9a68-6e7e-11e5-87bd-930046f1ac7b.png)

**Comment by IKCAP** [comment]
I’m afraid there was a bug with the previous domain that i just uploaded. Could you please update your domain again ? Sorry !

**Comment by olyerickson** [comment]
Updated!
![selection_476](https://cloud.githubusercontent.com/assets/358649/10399802/0a5f4956-6e83-11e5-8c6d-e81f371e8fe3.png)
