### ISSUE TITLE
Where/How do we view PROV of executed workflows?

### ISSUE THREAD

**Issue by olyerickson** [IKCAP/wings#22]
One of the things that excites us about using WINGS is the possibility of generating accurate and relevant PROV instance data. But I can't figure out how to see this...

**Comment by IKCAP** [comment]
[tomcat-server]/wings-portal/export/users/[userid]/[domain]/executions/[runid].owl

**Comment by olyerickson** [comment]
Which identifiers are the runids? 

For example, are the identifiers in these tabs the runids? 

Is there an easy way to copy/paste these? 
![selection_485](https://cloud.githubusercontent.com/assets/358649/10488128/304cb0e6-7265-11e5-8858-f442a46f2b1b.png)

**Comment by olyerickson** [comment]
I can't find a path on my machine matching this structure

**Comment by IKCAP** [comment]
Yes John, those are the runids. I didn’t realise that we couldn’t copy/paste them. The way I normally get the provenance url is by looking at the Developer tools window and the Network requests. See attached screenshot:

**Comment by olyerickson** [comment]
I'm not seeing a "Developer Tools" window...

**Comment by IKCAP** [comment]
Depends on your browser really. Javascript console maybe ? I use Google chrome to get this.

By the way, you wouldn’t find the results in file format in your machine. The RDF/OWL file is generated by the “Export” servlet by reading the internal TDB triple store. 

Example: 
http://www.wings-workflows.org/wings-portal/export/users/admin/DMDomain/executions/ModelThenClassif-056b018e-b77d-45b9-ab2c-734e191506c1.owl

All urls that start with export/.. are essentially sent over to the “Export” servlet, which reads the internal TDB triple store and returns and RDF/OWL serialization of the requested graph. All workflows, component descriptions, data descriptions, and run details are stored in the triple store, and accessible in the same way.

Regards,
Varun

**Comment by olyerickson** [comment]
Oh, THAT "Developer Tools!" ;) 

I was able to grab the runids but can't find anything on my machine with those names

**Comment by IKCAP** [comment]
Haha, yes. I should've been clearer earlier :-)

The run details are extracted from the run URL. So as long as you see the run details, the URL should be reference-able.

**Comment by olyerickson** [comment]
I now see that you were giving me a URL and not a file path. Using a runid ```Interleaved-57a0-83f38579-ad61-4b77-a91b-700c8f280fd1``` I was able to see the OWL!

**Comment by olyerickson** [comment]
Note that the web application installs with the name "wings-portal-4.0-SNAPSHOT" so the URL looks more like...

```http://localhost:8080/wings-portal-4.0-SNAPSHOT/export/users/olyerickson/CompareFiles_2_/executions/Interleaved-57a0-83f38579-ad61-4b77-a91b-700c8f280fd1.owl```

**Comment by IKCAP** [comment]
Great ! Sorry about the confusion !

**Comment by olyerickson** [comment]
Have you published your ontology for representing workflow execution? Sorry if it is on the WINGS website and I missed it

**Comment by olyerickson** [comment]
BTW here is a visualization I just did, depicting the workflow plan
![selection_486](https://cloud.githubusercontent.com/assets/358649/10490332/7e714c24-726e-11e5-9360-f5276f94f04a.png)

**Comment by olyerickson** [comment]
What are your plans w.r.t. PROV-O? ;)

**Comment by dgarijo** [comment]
Hi @olyerickson, what you posted seems to be the plan used to specify the run, but not the provenance itself. The ontology for publishing provenance of the workflows is at: http://www.opmw.org/ontology/. The ontology for specifying plans is published at http://purl.org/net/p-plan.

**Comment by dgarijo** [comment]
And the bit from the figure seems to be a particular extension of P-plan for capturing how the plans are invoked: http://purl.org/net/wf-invocation. I hope this helps.

**Comment by olyerickson** [comment]
This is great...thanks!

**Comment by IKCAP** [comment]
Thanks for the response Daniel !

@olyerickson: Daniel is involved with the provenance publishing module for Wings.

**Comment by olyerickson** [comment]
Closing this issue, because it has answered my initial provenance question(s)
