### ISSUE TITLE
Error compiling with maven

### ISSUE THREAD

**Issue by fhidalgl** [IKCAP/wings#28]
Hi!
I'm having problems compiling the project with maven. The error log is in the attached file, can you tell me what I am doing wrong?

Thank you!
[Log.txt](https://github.com/IKCAP/wings/files/174895/Log.txt)

**Comment by IKCAP** [comment]
Please try now. I've commented out an experimental engine compilation from the build.

**Comment by fhidalgl** [comment]
Hello,
I still have problems resolving dependencies :( 
"
Failed to execute goal on project wings-portal: Could not resolve dependencies for project edu.isi.wings:wings-portal:war:4.0-SNAPSHOT: Could not find artifact edu.isi.wings:wings-pegasus-adapter:jar:4.0-SNAPSHOT
"
Do I have to update the sorce code?
Thank you!

**Comment by IKCAP** [comment]
Yes please update the source from git.

**Comment by fhidalgl** [comment]
It didn't work. 
The last commit was 5 days ago, there may be some change without updating?

Thank you!

**Comment by IKCAP** [comment]
Could you check that your main wings pom.xml looks like the following:
https://github.com/IKCAP/wings/blob/master/pom.xml <https://github.com/IKCAP/wings/blob/master/pom.xml>

i.e. engines/pegasus module is commented out ?

Regards,
Varun

**Comment by fhidalgl** [comment]
The engine/pegasus module is not commented, I see no more difference.
[pom.xml.txt](https://github.com/IKCAP/wings/files/176010/pom.xml.txt)

It is also not commented the Wings the "Wings Pegasus Adapter" in Portal POM.

Thank you!

**Comment by fhidalgl** [comment]
ups! sorry. 
I was not working with the last version. In fact, the engine/pegasus module was commented in main wings pom.xml. 
I will try again.

Thank you!

**Comment by fhidalgl** [comment]
Hi!
It works!

Thank you!
