### ISSUE TITLE
I can't upload data .. HELP

### ISSUE THREAD

**Issue by Hadeelmas** [IKCAP/wings#35]
Hello, 
I have a problem and I hope you guys help me 
I have installed the standalone version of WINGS on my Linux Ubuntu machine..
I have been trying to create my own domain then my components and so on..
The problem I am having is when I created the component there was not an icon for uploading the code..
Then I tried just to upload my data file into one of the pr-defied components of Wordbag domain, but  
the uploading button was blocked.. 
I have attached a pic for you to see it ..
please I need to know what the problem is : (
Thanks 

![img_6167](https://cloud.githubusercontent.com/assets/25092440/21915342/51a623c6-d907-11e6-8af3-36a7c99521a7.JPG)

**Comment by IKCAP** [comment]
Hi there,

It seems that you are using a very old version of WINGS (looking at the address bar — wpmanagedata.html). Please use the latest version from github. 

Regards,
Varun
