### ISSUE TITLE
Can't see 'Admin' menu

### ISSUE THREAD

**Issue by SpencerNorris** [IKCAP/wings#39]
I'm currently working on Dockerizing WINGS at https://github.com/SpencerNorris/wings-docker . I'm able to access the portal as the admin user but WINGS doesn't display the 'Admin' menu that's supposed to be located across the top, so I can't check my resources for distributed execution. Anyone have a similar problem when running WINGS bare-metal?

**Comment by dgarijo** [comment]
Hi @SpencerNorris,
thanks for your interest!! 
we are currently testing a Docker image with WINGS as well. So far, I haven't had any trouble running and executing workflows.
It contains some tools that might not be interesting if you want a blank installation of WINGS, such as Tophat, cufflinks, R and Python. In any case, maybe you can give it a try and tell us if it solves your issues.

FROM r-base
MAINTAINER Varun Ratnakar <varunratnakar@gmail.com>
RUN sed -i 's/debian testing main/debian testing main contrib non-free/' /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y install graphviz curl unzip curl openssl libssl-dev libcurl4-openssl-dev libxml2-dev python-pip tomcat8
RUN apt-get -y install samtools tophat cufflinks
RUN pip install RSeQC
RUN mkdir -p /opt/wings/storage/default /opt/wings/server
ADD http://www.wings-workflows.org/downloads/docker/latest/portal/wings-portal.xml /etc/tomcat8/Catalina/localhost/wings-portal.xml
ADD http://www.wings-workflows.org/downloads/docker/latest/portal/portal.properties /opt/wings/storage/default/portal.properties
RUN cd /opt/wings/server && curl -O http://www.wings-workflows.org/downloads/docker/latest/portal/wings-portal.war && unzip wings-portal.war && rm wings-portal.war
RUN sed -i 's/Resource name="UserDatabase" auth/Resource name="UserDatabase" readonly="false" auth/' /etc/tomcat8/server.xml
RUN sed -i 's/=tomcat8/=root/' /etc/default/tomcat8
RUN sed -i 's/<\/tomcat-users>/  <user username="admin" password="4dm1n!23" roles="WingsUser,WingsAdmin"\/>\n<\/tomcat-users>/' /etc/tomcat8/tomcat-users.xml
ADD http://www.wings-workflows.org/downloads/docker/latest/domain/R-install.R /tmp/R-install.R
RUN Rscript /tmp/R-install.R
CMD service tomcat8 start && /bin/bash

**Comment by SpencerNorris** [comment]
Man, this is basically exactly what I was looking for. Thanks much!

**Comment by dgarijo** [comment]
No problem! I will close the issue then. Please re-open it if you have further questions.

**Comment by SpencerNorris** [comment]
Hey, having trouble using the Dockerfile above. Wind up with the following error:
```
The command '/bin/sh -c sed -i 's/</tomcat-users>/ <user username="admin" password="4dm1n!23" roles="WingsUser,WingsAdmin"/>\n</tomcat-users>/' /etc/tomcat8/tomcat-users.xml' returned a non-zero code: 1
```

Log for reference:
```
Sending build context to Docker daemon 3.584 kB

Step 1 : FROM r-base
 ---> 1c7b11f30258
Step 2 : MAINTAINER Varun Ratnakar varunratnakar@gmail.com
 ---> Using cache
 ---> a99268eb37ad
Step 3 : RUN sed -i 's/debian testing main/debian testing main contrib non-free/' /etc/apt/sources.list
 ---> Using cache
 ---> e57366aff5d3
Step 4 : RUN apt-get update
 ---> Using cache
 ---> 45801d816042
Step 5 : RUN apt-get -y install graphviz curl unzip curl openssl libssl-dev libcurl4-openssl-dev libxml2-dev python-pip tomcat8
 ---> Using cache
 ---> 9b8890566c0e
Step 6 : RUN apt-get -y install samtools tophat cufflinks
 ---> Using cache
 ---> b2a6dddbe49c
Step 7 : RUN pip install RSeQC
 ---> Using cache
 ---> 1a06132f1858
Step 8 : RUN mkdir -p /opt/wings/storage/default /opt/wings/server
 ---> Using cache
 ---> b34c12a995ad
Step 9 : ADD http://www.wings-workflows.org/downloads/docker/latest/portal/wings-portal.xml /etc/tomcat8/Catalina/localhost/wings-portal.xml

 ---> Using cache
 ---> 3e0572c561f1
Step 10 : ADD http://www.wings-workflows.org/downloads/docker/latest/portal/portal.properties /opt/wings/storage/default/portal.properties

 ---> Using cache
 ---> 995f58b9bf08
Step 11 : RUN cd /opt/wings/server && curl -O http://www.wings-workflows.org/downloads/docker/latest/portal/wings-portal.war && unzip wings-portal.war && rm wings-portal.war
 ---> Using cache
 ---> 4aefe295124b
Step 12 : RUN sed -i 's/Resource name="UserDatabase" auth/Resource name="UserDatabase" readonly="false" auth/' /etc/tomcat8/server.xml
 ---> Using cache
 ---> 25d92df5b576
Step 13 : RUN sed -i 's/=tomcat8/=root/' /etc/default/tomcat8
 ---> Using cache
 ---> bcfa42a421ed
Step 14 : RUN sed -i 's/</tomcat-users>/ <user username="admin" password="4dm1n!23" roles="WingsUser,WingsAdmin"/>\n</tomcat-users>/' /etc/tomcat8/tomcat-users.xml
 ---> Running in 1c477a46135b
[91msed: -e expression #1, char 20: unknown option to `s'
[0m
```

**Comment by SpencerNorris** [comment]
OK, more problems with the image. Getting the following issue, which I was having with the image I had built as well.
![workspace 1_008](https://cloud.githubusercontent.com/assets/7319127/23469763/8e5e37e6-fe72-11e6-9c26-5c2d843e032f.png)

**Comment by IKCAP** [comment]
Hi Spencer,

I believe this is a bug with the CompareFiles domain that we have put out there. To fix it, go to "Manage Components" in the interface, and select the html2text and pdf2text components, and remove the component dependencies.

**Comment by SpencerNorris** [comment]
Tried navigating to `Components`, this is what I got:
```
HTTP STATUS 500 -
type Exception report
message
description: The server encountered an internal error that prevented it from fulfilling this request.
exception
java.lang.NullPointerException
	edu.isi.wings.catalog.provenance.api.impl.kb.ProvenanceKB.end(ProvenanceKB.java:223)
	edu.isi.wings.portal.controllers.ComponentController.show(ComponentController.java:134)
	edu.isi.wings.portal.servlets.ManageComponents.doGet(ManageComponents.java:108)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:41)
	org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:268)
	org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
	edu.isi.wings.portal.filters.CORSFilter.doFilter(CORSFilter.java:26)
```

**Comment by dgarijo** [comment]
Hi @SpencerNorris,
was your issue solved? I have been able to create workflows with this Docker image successfully.

**Comment by SpencerNorris** [comment]
Hi @dgarijo and @IKCAP ,
Not just yet. It doesn't appear as if there are any dependencies set for the components. However, I started following the steps that were designated in Issue #21 and am making progress, so I think I'll follow those and see what happens.

**Comment by SpencerNorris** [comment]
Alright, after going through Issue #21 and doing some finagling, it seems to work. Here's the Dockerfile I'm using now:
```
FROM r-base
MAINTAINER Varun Ratnakar varunratnakar@gmail.com
RUN sed -i 's/debian testing main/debian testing main contrib non-free/' /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y install graphviz curl unzip curl openssl libssl-dev libcurl4-openssl-dev libxml2-dev python-pip tomcat8
RUN apt-get -y install samtools tophat cufflinks
RUN pip install RSeQC
RUN mkdir -p /opt/wings/storage/default /opt/wings/server
ADD http://www.wings-workflows.org/downloads/docker/latest/portal/wings-portal.xml /etc/tomcat8/Catalina/localhost/wings-portal.xml
ADD http://www.wings-workflows.org/downloads/docker/latest/portal/portal.properties /opt/wings/storage/default/portal.properties
RUN cd /opt/wings/server && curl -O http://www.wings-workflows.org/downloads/docker/latest/portal/wings-portal.war && unzip wings-portal.war && rm wings-portal.war
RUN sed -i 's/Resource name="UserDatabase" auth/Resource name="UserDatabase" readonly="false" auth/' /etc/tomcat8/server.xml
RUN sed -i 's/=tomcat8/=root/' /etc/default/tomcat8
RUN sed -i 's/<\/tomcat-users>/ <user username="admin" password="4dm1n!23" roles="WingsUser,WingsAdmin"\/>\n<\/tomcat-users>/' /etc/tomcat8/tomcat-users.xml
ADD http://www.wings-workflows.org/downloads/docker/latest/domain/R-install.R /tmp/R-install.R
RUN Rscript /tmp/R-install.R
RUN chown tomcat8:tomcat8 /etc/tomcat8/tomcat-users.xml
RUN mkdir /var/lib/tomcat8/temp && chown -R tomcat8:tomcat8 /var/lib/tomcat8/temp
RUN ln -sf bash /bin/sh
CMD service tomcat8 start && /bin/bash
```
How did you guys manage to run CompareFiles without these modifications though?

**Comment by dgarijo** [comment]
Hi @SpencerNorris,
when I tested the Docker file I created my own workflows and components. I ran them successfully, so I didn't import other domains. Thanks for sending us the fixed Docker file!!
