### ISSUE TITLE
dcdom namespace constraints do not show up.

### ISSUE THREAD

**Issue by alyssad149** [IKCAP/wings#57]
Steps to recreate issue:
1. Create a datatype
2. Add a metadata property
3. Save
4. Add a data file (not sure if you need to add it for it to work properly but do so just in case?)
5. Add properties to the file and save.
6. Create a component with the input with the datatype created.
7. Save and set the new input as the variable.
8. Click on the constraint dropdown.

In the dropdown there should be dcdom:hasPropertyCreated as an option. However, it does not appear after the above steps. 

Thanks!

**Comment by IKCAP** [comment]
Resolved via https://github.com/IKCAP/wings/commit/b1dece772dd171e0759c3274a77a56820b5bd3bf
